import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Terms and Conditions | Top4 Call Drivers',
    description: 'Terms and Conditions for Top4 Call Drivers.',
};

export default function TermsAndConditions() {
    return (
        <div className="bg-gray-50 min-h-screen py-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-4xl mx-auto bg-white shadow rounded-lg p-8">
                <h1 className="text-3xl font-bold text-gray-900 mb-8 border-b pb-4">Terms and Conditions</h1>

                <div className="prose prose-blue max-w-none text-gray-700 space-y-6">
                    <h2 className="text-xl font-bold text-gray-900">TOP 4 Hire Drivers TERMS & CONDITIONS</h2>
                    <p>
                        Welcome to our mobile application and / or our website.
                    </p>

                    <p>
                        This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.top4.in website and Top4 applications for mobile and handheld devices.
                    </p>

                    <p>
                        These terms and conditions of use (‘’Terms of Use’’) of the Top4 website and mobile app, is a legal agreement (&quot;Agreement&quot;) between Top4 Call Drivers Pvt Ltd and yourself/yourselves. If you continue to browse the website and/or use the mobile application you are agreeing to comply with and be bound by the Terms of Use.
                    </p>

                    <p>
                        If you do not agree with the Terms of Use, please do not access and use this Website / Application (as hereinafter defined) or our Service through all other means.
                    </p>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">1. DEFINITIONS:</h3>
                    <ul className="list-disc pl-5 space-y-2">
                        <li><strong>“Top4”, “we”, “our” and “us”</strong> shall mean Top4;</li>
                        <li><strong>“You”, yourself / yourselves and “your”</strong> shall mean a User, who meets the eligibility criteria set out below;</li>
                        <li><strong>“Application”</strong> shall mean the application supplied by Top4 and downloaded and installed by you on your single mobile device (smart phone);</li>
                        <li><strong>“Driver” or ‘’Drivers’’</strong> shall mean the driver engaged by you by using our Website/Application;</li>
                        <li><strong>“Force Majeure”</strong> shall have the meaning as set out in Clause VII;</li>
                        <li><strong>“Service” or “Services”</strong> shall mean the service of providing short-term private Driver solutions via the Application/Website as defined in Clause I;</li>
                        <li><strong>‘’User’’ or ‘’Users’’</strong> shall have the meaning as set out in Clause III; and</li>
                        <li><strong>‘’Website’’</strong> shall mean the website www.top4.in.</li>
                    </ul>

                    <p>
                        These Terms of Use may be modified from time to time in our sole discretion. It is your responsibility to review these Terms and Conditions from time to time. If you continue to use the Service after notice of change has been intimated or published on our Website/Application, you thereby provide your consent to the changed practices on the same terms hereof. For this reason, we encourage you to review these Terms of Use each time you access and use the Website/Application. Most content and some of the features on the Website/Application are made available to Users free of charge. However, Top4 reserves the right to terminate access to certain areas or features of the Website/Application at any time for any reason, with or without notice.
                    </p>

                    <p>
                        If you are not agreeable to these Terms of Use, you may not use the Services, the Website or the Application.
                    </p>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">2. SERVICES DESCRIPTION:</h3>
                    <ol className="list-decimal pl-5 space-y-2">
                        <li>Top4 Call Drivers Private Limited operates a technology based electronic platform service called ‘Top4’ which seeks to provide drivers-on-demand to customers who wish to obtain the services of a driver.</li>
                        <li>Top4 enables the hiring of drivers by commuters/ passengers for a point to point pick up and drop off Service, within city limits and outside city limits, through the Application in mobile telecommunications devices and through the Website. The Service is designed to offer you information and a means of obtaining short-term private driver solutions to coordinate point-to-point and round-trip private driver services, at user’s request. As a User, you authorize the opted Driver to operate your vehicle and make decisions on your behalf during a period of time designated by you.</li>
                        <li>The Drivers offering their services on the Top4 platform are individuals and independent service providers who have opted to enlist themselves with Top4. The drivers are screened and trained prior to being listed as a driver on the Top4 platform. At no point can the driver represent himself to be an employee of Top4 Call Drivers Private Limited/Top4. The user terms and conditions in here expressly provide that the drivers are independent service providers and are not employees of Top4 Call Drivers Private Limited/Top4.</li>
                        <li>Further, it is to be noted that Top4, in itself does not provide driving / transportation services. The customer offers the mode of transportation. The terms and conditions clearly state that the provision of services by the driver to the customer is, subject to the agreement entered into between them and Top4 shall under no circumstance be a party to such agreement.</li>
                        <li>To elaborate, the modus operandi is as follows:
                            <ul className="list-[lower-alpha] pl-5 mt-2 space-y-1">
                                <li>‘Top4’ aims at bringing drivers/operators (service providers) and customers owning private cars on a common platform by which the said customers can place a request for the services of a professional driver for commute.</li>
                                <li>The e-commerce platform brings the customer into contact with a driver so as to avail the latter’s services, subject to the availability of drivers in or around the customer’s location at the time of registering his request.</li>
                                <li>The request by the customer could be for a point-to-point commute or a round trip is placed by the customer electronically over a mobile based app or through an online website operated by Top4 or via phone service.</li>
                                <li>Towards the end of the commute, the customers are charged for the services of the driver, which is intimated to them over the app or mail. The services may be paid for by the customers either:
                                    <ul className="list-disc pl-5 mt-1">
                                        <li>in cash, directly to the driver or</li>
                                        <li>through online payment options, to Top4</li>
                                    </ul>
                                </li>
                                <li>Where the customer opts to pay for the drivers’ services through any of the online modes available on the app, Top4 remits the proceeds collected from the customers to the respective drivers.</li>
                                <li>In return for the use of the Top4’s electronic platform, the Drivers are charged a convenience fee by Top4. Top4 remits any applicable tax to the credit of the respective Governments and regularly files periodic returns as prescribed under the GST laws.</li>
                            </ul>
                        </li>
                    </ol>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">3. USE OF SERVICE, APPLICATION AND WEBSITE:</h3>
                    <p>
                        The Application and the Website allows you to send a request for Service to a Driver. The GPS receiver, which should be installed on the mobile device (smart phone) on which you have downloaded the Application or the Website, shall detect your location and shall send your location information to the relevant Driver. Top4 has sole and complete discretion to accept or reject each request for providing the Service. Top4 also has sole and complete discretion over whether to use the Application / Website to receive the leads generated through the Application / Website. If Top4 accepts a request, the Application / Website notifies you and provides information regarding the Driver - including his name and the ability to contact the Driver by telephone or a message. The Application / Website also allow you to view the Driver’s progress towards the pick-up point, in real time.
                    </p>
                    <p>
                        Top4 shall undertake commercially reasonable efforts to bring you into contact with a Driver in order to avail the Services, subject to the availability of Drivers in or around your location at the moment of your request for the Services.
                    </p>
                    <p>
                        Top4 itself does not provide transportation services. It is up to the User to offer transportation. Top4 only acts as intermediary between the Driver and you. The provision of the Services by the Driver to you is, therefore, subject to the agreement (to be) entered into between the Driver and you. Top4 shall under no circumstance be a party to such agreement. Top4 disclaims any and all liability in respect of the Drivers including any claims of employment or any vicarious liability arising out of the Service or otherwise.
                    </p>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">4. USER ELIGIBILITY AND AGREEMENT:</h3>
                    <p>
                        User means any individual or business entity/organization that legally operates in India or in other countries, and uses and has the right to use the Services provided by Top4. Our Services are available only to those individuals or entities who can execute legally binding contracts under the applicable law. Therefore, a User must not be a minor as per Indian Law; i.e. User(s) must be at least 18 years of age to be eligible to use our Services.
                    </p>
                    <p>
                        Top4 advises its Users that while accessing the Website/Application, they must follow/abide by the applicable laws. Top4 may, in its sole discretion, refuse the Service to anyone at any time.
                    </p>
                    <p>
                        This Agreement applies to all Services offered on the Website/Application, collectively with any additional terms and condition that may be applicable.
                    </p>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">5. REGISTRATION:</h3>
                    <p>
                        To use the Services, you have to be registered and provide your name, contact number, email address and other details. Please see our Privacy Policy and practices to know more about how your personal information would be used.
                    </p>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">6. REPRESENTATIONS AND WARRANTIES:</h3>
                    <p>As a precondition to your use of the Services, you represent and warrant that:</p>
                    <ul className="list-disc pl-5 space-y-2">
                        <li>The information you provide to Top4 is accurate and complete. Top4 service is only available for private cars for non-commercial purposes within the city limits as designated on our Website. Private cars for non-commercial purposes bear license plates with black lettering over white colored background (Commercial vehicles have license plates with black lettering over yellow colored background). You will ensure that Top4 service is being utilized only for non-commercial purposes in a private car. Top4 is entitled, at all times, to verify the information that you have provided and to refuse the Service or use of the Application / Website without providing reasons.</li>
                        <li>You will only access the Service using authorized means. You are responsible to check and ensure you download the correct Application for your device or the correct Website in your computer. Top4 shall not be liable if you do not have a compatible mobile device or if you download the wrong version of the Application for your mobile device or Website for the computer. Top4 reserves the right to terminate the Service and the use of the Application/ Website should you use the Service or Application with an incompatible or unauthorized device.</li>
                        <li>You have the legal right and authority to possess and operate the vehicle when engaging our Services and you confirm, represent and warrant that the said vehicle is in good operating condition and meets the industry safety standards and all applicable statutory requirements for a motor vehicle of its kind.</li>
                        <li>You will be solely responsible for any and all liability which results from or is alleged as a result of the condition of your vehicle, legal compliance, etc., including, but not limited to, personal injuries, death and property damages.</li>
                        <li>You will be solely responsible for the full functionality of your vehicle. If your vehicle fails to function (electrical, mechanical or other) in any way while the Services are being availed of by you, you will be responsible for all storage fees, roadside assistance, alternate transportation and repair of any kind and neither Top4 nor the Driver shall be responsible in any manner whatsoever. You have the legal right to designate the Driver as your agent and delegate actual authority to the Driver to operate your vehicle and make decisions on your behalf for the purposes of providing Services offered through the Top4 platform.</li>
                        <li>You are named or scheduled on the insurance policy covering the vehicle you use when engaging our Services. You have a valid policy of liability insurance (in coverage amounts consistent with all applicable legal requirements) for the operation of your vehicle to cover any anticipated losses related to your participation in the Services or the operation of your vehicle by the Driver. In the event of a motor vehicle accident you will be solely responsible for compliance with any applicable statutory or department of motor vehicles requirements and for all necessary contacts with your insurance provider. Other than any personal criminal liability attaching to the Driver you will be solely responsible for all consequences arising out of the use of the Service or the Driver. In any event Top4 shall have no responsibility or liability on this account whatsoever.</li>
                        <li>You specifically authorize us to use, store or otherwise process your &apos;Sensitive personal data or information’ (as such term is defined in Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011) in order to provide the Services to you. Subject to applicable law all information provided to us by you shall be deemed to be our information to use as we desire.</li>
                        <li>You will obey all applicable laws related to the matters set forth herein and will be solely responsible for any violations of the same.</li>
                    </ul>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">7. METER START AND CANCELLATION POLICY:</h3>
                    <p>Top4 drivers will wait no more than 15 minutes from the requested trip start time, before they start the trip timer.</p>
                    <p>You can cancel a driver service booking any time through the Top4 App or Website but may be charged a cancellation fee if you cancel after the driver is already on the way.</p>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">8. PAYMENT</h3>
                    <p>When a trip ends, Top4 driver ends the trip on the Top4 Partner app on his mobile device. It then calculates the total fare amount due from You and it appears on the Top4 app on your mobile device. You may pay the amount via cash or a variety of online payment options available on the app. Any payment related issue, except when such issue is due to an error or fault in the Site or Application, shall be resolved between You and the payment processor.</p>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">9. LIMITATION OF LIABILITY:</h3>
                    <p>The information, recommendations and/or Services provided to you on or through the Website/Application are for general information purposes only and do not constitute advice. Top4 will take reasonable steps to keep the Website/Application and its contents correct and up to date but does not guarantee that the contents of the Website/Application are free of errors, defects, malware and viruses or that the Website/Application are correct, up to date and accurate.</p>
                    <p>Top4 shall not be liable for any damages resulting from the use of, or inability to use, the Website/Application, including damages caused by malware, viruses or any incorrectness or incompleteness of the information on the Website/Application.</p>
                    <p>Top4 shall further not be liable for damages resulting from the use of, or the inability to use, electronic means of communication with the Website/Application, including — but not limited to — damages resulting from failure or delay in delivery of electronic communications, interception or manipulation of electronic communications by third parties or by computer programs used for electronic communications and transmission of viruses.</p>
                    <p>Without prejudice to the foregoing, and insofar as allowed under mandatory applicable law, Top4’s aggregate liability shall in no event exceed the equivalent of the amount for the payment of the Services.</p>
                    <p>The quality of the Services requested through the use of the Application is entirely the responsibility of the Driver who ultimately provides such transportation services to you. Top4 under no circumstance accepts liability in connection with and/or arising from the Services provided by the Driver or any acts, actions, behaviour, conduct, and/or negligence on the part of the Driver.</p>
                    <p>We shall not be held liable for any failure or delay in performing Services where such failure arises as a result of any act or omission, which is outside our reasonable control such as unprecedented circumstances, overwhelming and unpreventable events caused directly and exclusively by forces of nature that can be neither anticipated, nor controlled, nor prevented by the exercise of prudence, diligence, and care, including but not limited to: war, riot, civil commotion; compliance with any law or governmental order, rule, regulation or direction and acts of third parties ( “Force Majeure” ).</p>
                    <p>If we have contracted to provide identical or similar Service to more than one User and are prevented from fully meeting our obligations to you by reason of an event of Force Majeure, we may decide at our absolute discretion which booking we will fulfill by providing the Service, and to what extent.</p>
                    <p>We have taken all reasonable steps to prevent internet fraud and ensure any data collected from you is stored as securely and safely as possible. However, we shall not be held liable in the unlikely event of a breach in our secure computer servers or those of third parties other than as required under applicable law.</p>
                    <p>In the event we have a reasonable belief that there exists an abuse of vouchers and/or discount codes or suspect an instance of fraud, we may cause the User to be blocked immediately and reserve the right to refuse future Service. Additionally, should there exist an abuse of vouchers or discount codes, Top4 reserves the right to seek compensation from any and all such Users.</p>
                    <p>Top4 does not represent or endorse the accuracy or reliability of any information, or advertisements (collectively, the &quot;Content&quot;) contained on, distributed through, or linked, downloaded or accessed from or contained on the Website/Application, or the quality of any products, information or other materials displayed, or obtained by you as a result of an advertisement or any other information or offer in or in connection with the Service.</p>
                    <p>Offers are subject to Top4&apos;s discretion and may be withdrawn at any time and without notice.</p>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">10. INTELLECTUAL PROPERTY RIGHTS:</h3>
                    <p>Top4 is the sole owner or lawful licensee of all the rights to the Website/Application and its content. Website/Application content means its design, layout, text, images, graphics, sound, video etc. The Website/Application content embodies trade secrets and intellectual property rights protected under worldwide copyright and other laws. All title, ownership and intellectual property rights in the Website/Application and its content shall remain with Top4.</p>
                    <p>All rights, not otherwise claimed under this Agreement or in the Website /Application, are hereby reserved. The information contained in this Website/Application is intended, solely to provide general information for the personal use of the reader, who accepts full responsibility for its use.</p>
                    <p>You may access the Website/Application, avail of the features, facilities and Services for your personal or internal requirements only. You are not entitled to duplicate, distribute, create derivative works of, display, or commercially exploit the Website/Application Content, features or facilities, directly or indirectly, without our prior written permission of Top4.</p>

                    <h4 className="font-semibold mt-4">Copyright</h4>
                    <p>All content on this Website/Application is the copyright of Top4 except the third party content and link to third party website on our Website/Application, if any.</p>
                    <p>Systematic retrieval of Top4 content to create or compile, directly or indirectly, a collection, compilation, database or directory (whether through robots, spiders, automatic devices or manual processes) without written permission from Top4 is prohibited.</p>
                    <p>In addition, use of the content for any purpose not expressly permitted in this Terms of Use is prohibited and may invite legal action. As a condition of your access to and use of Services, you agree that you will not use the Website/Application to infringe the intellectual property rights of others in any way. Top4 reserves the right to terminate the account of a User upon any infringement of the rights of others in conjunction with use of the Service, or if Top4 believes that User’s conduct is harmful to the interests of Top4, its affiliates, or other Users, or for any other reason in Top4&apos;s sole discretion, with or without cause.</p>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">11. USER ACCOUNTS, OFFERS AND PROMOTIONS:</h3>
                    <p>Top4 reserves the right to collect User data including name, contact information and other details to facilitate Services or use of its platform to avail Services. All information collected from the User are on a bona fide basis. Misuse and misrepresentation of identity or contact details will lead to automatic termination of Services or the use of the platform, without prior notice to such Users.</p>
                    <p>User accounts bearing contact number and email IDs are created and owned by Top4. Any promotional discounts and offers accumulated can be revoked without prior notice in the event of suspicious account activity or mala fide intent of the User.</p>
                    <p>In the case where the system is unable to establish unique identity of a User against a valid mobile number or e-mail ID, the account shall be indefinitely suspended. Top4 reserves the full discretion to suspend a User&apos;s account in the above event and does not have the liability to share any account information whatsoever.</p>
                    <p>For any other queries on Top4 and its services, please write in to us at <a href="mailto:info@top4calldrivers.com" className="text-blue-600 hover:text-blue-800">info@top4calldrivers.com</a></p>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">12. LINKS TO THIRD PARTY SITES:</h3>
                    <p>Links to third party sites are provided by the Application / Website as a convenience to Users and Top4 does not have any control over such sites i.e., content and resources provided by them.</p>
                    <p>Top4 may allow Users access to content, products or services offered by third parties through hyperlinks (in the form of word link, banners, channels or otherwise) to such third party&apos;s website. You are cautioned to read such sites&apos; terms and conditions and/or privacy policies before using such sites in order to be aware of the terms and conditions of your use of such sites. The Users acknowledge that Top4 has no control over such third party&apos;s site, does not monitor such sites, and Top4 shall not be responsible or liable to anyone for such third party site, or any content, products or services made available on such a site.</p>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">13. TERMINATION:</h3>
                    <p>Top4 reserves the right to deny access to particular Users to any/all of its Services without any prior notice/explanation in order to protect the interests of Top4 and/or other Users to the Website/Application. Top4 reserves the right to limit, deny or create different access to the Website/Application and its features with respect to different Users.</p>
                    <p>We reserve the right to terminate your account or your access to the Website/Application immediately, with or without notice to you, and without liability: (i) if you have violated any of the Terms of Use; (ii) if you have furnished us with false or misleading information; (iii) pursuant to requests by law enforcement or other government agencies; (iv) in case of unexpected technical or security issues or problems; (v) in case of discontinuance or material modification to the Services (or any part thereof); and / or (vi) in case of interference with use of our Website/Application by others.</p>
                    <p>In the event of termination by you or us, your account will be disabled and you will not be granted access to your account or any information or content contained in your account. You will not and not attempt to create another account for accessing and using the Website/Application without the written consent of Top4.</p>
                    <p>This Terms of Use shall remain in full force and effect while you have an account with us. Even after termination of your account with us, certain provisions of this Terms of Use will remain in effect, including but not limited to, Intellectual Property Rights, Prohibited Uses and Indemnification. You agree that we will not be liable to you or any third party for taking any of these actions.</p>
                    <p>Notwithstanding the termination of this Agreement, you shall continue to be bound by the terms of this Agreement in respect of your prior use of this Website/Application and all matters connected with, relating to or arising from such use.</p>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">14. TERMS & CONDITIONS FOR USE OF SERVICES:</h3>
                    <p>The following terms & conditions shall apply to Users utilising the Services offered by Top4:</p>
                    <ul className="list-disc pl-5 space-y-2">
                        <li>The User shall pay the driver fare (as displayed in the Top4 App) or as agreed to in the terms of use as listed on the Application / Website, parking charges, additional night surcharge (where applicable), one way trips, toll charges and any fee or levy presently payable or hereinafter imposed by the law or required to be paid for availing of the Services.</li>
                        <li>The User agrees and accepts that the use of the Services provided by Top4 is at the sole risk of the User, and further acknowledges that Top4 disclaims all representations and warranties of any kind, whether express or implied. All Services are provided “AS IS”.</li>
                        <li>The Top4 or the Driver has the right to refuse the Service in the following circumstances:
                            <ul className="list-[circle] pl-5 mt-1 space-y-1">
                                <li>if the User is found to be in an intoxicated state or is found misbehaving with other passengers or the Driver, or is causing a nuisance;</li>
                                <li>if the User is misusing, soiling or damaging any of the devices (technical/non-technical) of the Driver; and if the User asks the Driver to break any traffic/RTO/city police and/or government rules for any purpose The Driver has the right to refuse such a request by the User.</li>
                            </ul>
                        </li>
                        <li>Without prejudice to the above, Top4 makes no representation or warranty that:
                            <ul className="list-[circle] pl-5 mt-1 space-y-1">
                                <li>the Services will meet the User’s requirements; and</li>
                                <li>the Services will be uninterrupted, timely, secure, or error-free.</li>
                            </ul>
                        </li>
                        <li>The information on this Website/Application is provided &quot;AS IS&quot; with no guarantee of completeness, accuracy, timeliness or of the results obtained from the use of this information, and without warranty of any kind, express or implied, including, but not limited to warranties of performance, merchantability and fitness for a particular purpose. Nothing herein shall to any extent substitute for the independent investigations and the sound technical and business judgment of the Users. In no event shall Top4 be liable for any direct, indirect, incidental, punitive, or consequential damages of any kind whatsoever with respect to the Service. Users of this site must hereby acknowledge that any reliance upon any content shall be at their sole risk. If any User misses his/her train or flight or bus, Top4 will not be liable for any compensation.</li>
                        <li>Top4 is hereby authorized to use the location-based information provided by any of the telecommunication companies when the User uses the mobile phone to make a booking. The location-based information will be used only to facilitate and improve the probability of locating a Driver for the User.</li>
                        <li>Top4 shall be entitled to disclose to any government body the particulars of the User in the possession, in its absolute discretion.</li>
                        <li>Top4 shall be entitled at any time without giving any reason to terminate the booking of Drivers done by the User.</li>
                        <li>If the User has any complaints in respect of the Services or the use of the Driver, the User has to inform Top4 of the same in writing within 24 hours of using the Driver or the Services.</li>
                        <li>Top4 shall not be liable for any conduct of the Drivers. However, Top4 encourages you to notify it of any complaints that you may have against any Driver or the Services.</li>
                    </ul>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">15. INSURANCE AND DAMAGE TO PROPERTY:</h3>
                    <p>Top4 we are not responsible for, damage or loss of any personal belongings or intellectual property whilst providing the Services. These include tapes, records, discs or other similar audio visual or data electronic devices, any speed measuring equipment within the vehicle or any other accessories of any kind. It is your responsibility to ensure that you remove any personal belongings from the car before and after each Top4 service arranged through Top4.</p>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">16. INDEMNITY:</h3>
                    <p>The User shall defend, indemnify and hold, Top4, its affiliates, its licensors, and each of their officers, directors, other users, employees, attorneys and agents, harmless, from and against any and all claims, costs, damages, losses, liabilities and expenses (including attorneys&apos; fees and costs) arising out of or in connection with the:</p>
                    <ul className="list-disc pl-5 space-y-1">
                        <li>violation or breach of the Terms of Use or any applicable law or regulation, whether or not referenced herein;</li>
                        <li>violation of any rights of any third party, including the Driver via the Application and or the Website; and</li>
                        <li>use or misuse of the Application/Website or Service.</li>
                    </ul>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">17. MISCELLANEOUS</h3>
                    <p>The information contained in this Website/Application is for general information purposes only. The information is provided by Top4 and while we endeavor to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the Website/Application or the information, products, services, or related graphics contained on the Website/Application for any purpose. Any reliance you place on such information is, therefore, strictly at your own risk.</p>
                    <p>In no event will we be liable for any loss or damage, including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this Website/Application or Service.</p>
                    <p>Every effort is made to keep the Website/Application up and running smoothly. However, Top4 takes no responsibility for, and will not be liable for, the Website/Application being unavailable due to technical issues beyond our control.</p>
                    <p>The above mentioned Terms of Use and the Privacy Policy constitute the entire agreement between the User and Top4 with respect to access to and use of the Website/ Application and the Services offered by Top4, superseding any prior written or oral agreements in relation to the same subject matter herein.</p>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">18. JURISDICTION:</h3>
                    <p>The courts of Chennai, India shall have the sole and exclusive jurisdiction in respect of any matters arising from the use of the Services offered by Top4 or the Terms of Use or any arrangement between Top4 and the User.</p>
                    <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. By registering at or merely browsing on Our Site you have agreed to be bound by all of these Terms and Conditions of Service for use and access of the Site. PLEASE ENSURE THAT YOU READ AND UNDERSTAND ALL THESE TERMS AND CONDITIONS BEFORE YOU USE ANY OF THE SERVICES OFFERED ON THE SITE, BECAUSE YOU SHALL BE BOUND BY ALL THE TERMS AND CONDITIONS CONTAINED HEREIN. If You do not accept any of the Terms and Conditions, then please don’t use the Site or avail any of the Services being provided therein</p>
                    <p>YOU AGREEING TO THESE TERMS AND CONDITIONS SHALL OPERATE AS A BINIDNG AGREEMENT BETWEEN YOU AND Top4 IN RESPECT OF THE SERVICES OFFERED/AVAILED USING THE SITE</p>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">2.5 Eligibility.</h3>
                    <ul className="list-[lower-alpha] pl-5 space-y-2">
                        <li>You will be &quot;Eligible&quot; to use Our Services only when You fulfill the following conditions:
                            <ul className="list-[lower-alpha] pl-5 mt-1">
                                <li>have attained at least 18 (eighteen) years of age;</li>
                                <li>are competent to enter into a contract under the Applicable Laws.</li>
                            </ul>
                        </li>
                        <li>You can avail the Services only if You fulfill the conditions as mentioned in a) to above.</li>
                        <li>If You are not Eligible, please immediately abandon any and all attempts to register with Us.</li>
                        <li>We rely completely on the information provided by You and We shall not be held liable if You or anyone who uses Your Account or Top4 is not Eligible.</li>
                        <li>As a minor if You wish to avail the Services, such Services may be availed by your legal guardian or parents who have registered as users on the Site.</li>
                        <li>Notwithstanding anything contained under these T&Cs, We reserve the right to terminate Your membership and refuse to provide You with access to the Site or provide Services if it is brought to Our notice or if it is discovered that You are under the age of 18 years or are incompetent to contract as per Applicable Laws.</li>
                    </ul>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">2.6 Registration.</h3>
                    <ul className="list-[lower-alpha] pl-5 space-y-2">
                        <li>You can register as a Customer, by providing a valid phone number, Your name, valid and functional e-mail address and any other additional information that RBI Regulations may prescribe to be necessary to satisfy Know Your Customer norms (&quot;KYC Norms&quot;), or other information as We may deem fit. (“Registration Data”).</li>
                        <li>You shall ensure that the Registration Data provided by You must be accurate, complete, current and true. We shall bear no liability for false, incomplete, old or incorrect Registration Data provided by You.</li>
                        <li>You hereby expressly consent to receive communications from Us through Your registered phone number and/or e-mail id. You consent to be contacted by Us via phone calls/SMS notifications. You agree that any communication so received by You from Us will not amount to spam, unsolicited communication or a violation of Your registration on the national do not call registry.</li>
                        <li>You are solely responsible for maintaining the confidentiality of Your Registration Data and will be liable for all activities and Transactions that occur through Your Account and Top4, whether initiated by You or any third party. The password and other details of the Account should not be shared with any third party. Your Account is non-transferable and is not capable of being sold to a third party. We shall not be liable for any loss that You may incur as a result of someone else using Your password or Account or accessing Your device, either with or without Your knowledge.</li>
                        <li>In the event of any change in the said information, You agree to promptly update Your Account information to ensure that the communications We intend to send to You are promptly delivered to You and are not sent to any other entity/third party.</li>
                        <li>We reserve the right to suspend or terminate Your Account with immediate effect and for an indefinite period, if We have a reason to believe that the Registration Data or any other data provided by You is incorrect or false, or that the security of Your Account has been compromised in any way. We reserve the right to suspend or terminate Your Account for reasons including and not limited to any fraud charges against You raised by the bank or concerned authorities and We also reserve the right to share Your information with them for the purposes of investigation.</li>
                        <li>We allow You to open only one Account in association with Registration Data provided by You.</li>
                        <li>In case of any unauthorized use of Your Account please immediately reach Us at <a href="mailto:info@top4calldrivers.com" className="text-blue-600 hover:text-blue-800">info@top4calldrivers.com</a></li>
                        <li>In case, You are unable to access Your Account, please inform Us at <a href="mailto:info@top4calldrivers.com" className="text-blue-600 hover:text-blue-800">info@top4calldrivers.com</a> and make a written request for blocking Your Account. We will not be liable for any unauthorized transactions made through Your Account prior to You making a request in writing for blocking and We shall require at least 72 (Seventy Two) hours to process your request unless in case of force majeure events which are beyond Our reasonable control.</li>
                    </ul>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">2.7 Use of Site</h3>
                    <p>You agree, undertake and confirm that Your use of Site shall be strictly governed by the following binding principles:</p>
                    <ul className="list-disc pl-5 space-y-2">
                        <li>You shall not host, display, upload, modify, publish, transmit, update or share any information that:
                            <ul className="list-disc pl-5 mt-1 space-y-1">
                                <li>belongs to another person and to which You do not have any right to; or interferes with another user&apos;s use and enjoyment of the Site or any other individual&apos;s user and enjoyment of similar services; or</li>
                                <li>that is harmful, harassing, blasphemous, defamatory, obscene, pornographic, libelous, invasive of another&apos;s privacy, hateful, or ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever, or unlawfully threatening or unlawfully harassing including but not limited to &quot;indecent representation of women&quot; within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986, of another person; or</li>
                                <li>misleading in any way; or</li>
                                <li>is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, pedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual; or</li>
                                <li>involves the transmission of &quot;junk mail,&quot; &quot;chain letters,&quot; or unsolicited mass mailing or &quot;spamming&quot;; or</li>
                                <li>infringes upon or violates any third party&apos;s rights, (including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person&apos;s name, email address, physical address or phone number) or rights of publicity]; or</li>
                                <li>contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page); or</li>
                                <li>provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone; or</li>
                                <li>provides instructional information about illegal activities such as making or buying illegal weapons, violating someone&apos;s privacy, or providing or creating computer viruses; or</li>
                                <li>contains video, photographs, or images of another person without his or her express written consent and permission or the permission or the consent of his/ her guardian in the case of minor; or</li>
                                <li>tries to gain unauthorized access or exceeds the scope of authorized access (as defined herein and in other applicable Codes of Conduct or End User Access and License Agreements) to the Sites or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Sites or solicits passwords or personal identifying information for commercial or unlawful purposes from other users; or</li>
                                <li>engages in commercial activities and/or sales without Our prior written consent such as contests, sweepstakes, barter, advertising and pyramid schemes, or the buying or selling of &quot;virtual&quot; items related to the Sites. Throughout these T&Cs, Our &quot;prior written consent&quot; means a communication coming from Our authorized representative, specifically in response to Your request, and specifically addressing the activity or conduct for which You seek authorization; or</li>
                                <li>interferes with another user&apos;s use and enjoyment of the Site or any other individual&apos;s user and enjoyment of similar services; or</li>
                                <li>refers to any website or URL that, in Our sole discretion, contains material that is inappropriate for the Site, contains content that would be prohibited or violates the letter or spirit of these T&Cs; or</li>
                                <li>harm minors in any way; or</li>
                                <li>is fraudulent or involve the sale of counterfeit or stolen items; or</li>
                                <li>violates any law for the time being in force; or</li>
                                <li>deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature; or</li>
                                <li>impersonate another person; or</li>
                                <li>contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any Trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal identifiable information or attempt to interfere with the proper working of the Site or any transaction being conducted on the Site; or</li>
                                <li>threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting to any other nation; or</li>
                                <li>is false, inaccurate or misleading; ordirectly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force; or</li>
                                <li>creates liability for Us or cause Us to lose (in whole or in part) the services of Our ISPs or other suppliers.</li>
                            </ul>
                        </li>
                        <li>You shall not use any &quot;deep-link&quot;, &quot;page-scrape&quot;, &quot;robot&quot;, &quot;spider&quot; or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Site or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Site or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Site. We reserve the right to bar any such activity.</li>
                        <li>You shall not probe, scan or test the vulnerability of the Site or any network connected to the Site nor breach the security or authentication measures on the Site or any network connected to the Site. You may not reverse look-up, trace or seek to trace any information on any other user of or visitor to the Site, or any other customer of DriveU, including any of Our account not owned by You, to its source, or exploit the Site or any service or information made available or offered by or through the Site, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than your own information, as provided for by the Site.</li>
                        <li>You agree that You will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Site or Our systems or networks, or any systems or networks connected to the Site.</li>
                        <li>You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal You send to Us on or through the Site or any service offered on or through the Site. You may not pretend that You are, or that You represent, someone else, or impersonate any other individual or entity.</li>
                        <li>You may not use the Site or any Content for any purpose that is unlawful or prohibited by these T&Cs, or to solicit the performance of any illegal activity or other activity that infringes the rights of Top4 or others.</li>
                        <li>You shall not use the Services or Site in any manner that could damage, disable, overburden, block or impair any of the server connected to the Site. You may not attempt to gain unauthorized access to the Services through hacking, password mining or any other means.</li>
                        <li>You may not reverse engineer, decompile and disassemble any software used to provide the Services.</li>
                        <li>You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about Us or the brand name or domain name used by Us or otherwise engage in any conduct or action that might tarnish the image or reputation, of Top4 or its merchants on platform or otherwise tarnish or dilute any of Our trade or service marks, trade name and/or goodwill associated with such trade or service marks, trade name as may be owned or used by Us.</li>
                        <li>You have the option to request Us to send You information regarding services, discounts and promotions provided by Us. If you require Us to provide You information from Us regarding offers, discounts and promotions relating to the Services availed by You, click &quot;Yes&quot;, otherwise click &quot;No&quot;. If you click &quot;Yes&quot;, We or an authorised representative, shall provide the above information to You by way of an SMS or email to Your registered mobile number/registered email id. You also have the option to discontinue receiving such information at any point of time. To discontinue receiving such information, You may at any point of time visit the specific link provided in Our Site to discontinue the same. Solely to enable Us to use the information so that We are not violating any rights You might have in Your Information, You agree to grant Us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights You have in Your Information, in any media now known or not currently known, with respect to Your Information. We will only use Your Information in accordance with these T&Cs and Our Privacy Policy.</li>
                        <li>You shall not engage in advertising to, or solicitation of, other users of the Site to buy or sell any products or services, including, but not limited to, services related being displayed on or related to the Site. You may not transmit any chain letters or unsolicited commercial or junk email to other users via the Site. It shall be a violation of these T&Cs to use any information obtained from the Site in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to another person outside of the Site without Our prior explicit consent. In order to protect Our users from such advertising or solicitation, We reserve the right to restrict the number of messages or emails which a user may send to other users in any 24-hour period which We may deem appropriate in Our sole discretion.</li>
                        <li>You understand that We have the right at all times to disclose any information (including the identity of the persons providing information or materials on the Site) as necessary to satisfy any law, regulation or valid governmental request. This may include, without limitation, disclosure of the information in connection with investigation of alleged illegal activity or solicitation of illegal activity or in response to a lawful court order or subpoena. In addition, We can (and You hereby expressly authorize Us to) disclose any information about You to law enforcement or other government officials, as We, in Our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury.</li>
                        <li>We reserve the right, but have no obligation, to monitor the materials posted on the Site. We shall have the right to remove or edit any Content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these T&Cs. Notwithstanding this right of Top4, YOU REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIALS YOU POST ON THE SITE AND IN YOUR PRIVATE MESSAGES. Please be advised that such Content posted does not necessarily reflect Our views. In no event shall We assume or have any responsibility or liability for any Content posted or for any claims, damages or losses resulting from use of Content and/or appearance of Content on the Site. You hereby represent and warrant that You have all necessary rights in and to all Content You provide and all information it contains and that such Content shall not infringe any proprietary or other rights of third parties or contain any libelous, tortious, or otherwise unlawful information.</li>
                        <li>Your correspondence or business dealings with, or participation in promotions of, third party advertisers found on or through the Site, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between You and such third party advertiser. We shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such third party advertisers on the Site.</li>
                        <li>It is possible those other users (including unauthorized users or “hackers”) may post or transmit offensive or obscene materials on the Site and that You may be involuntarily exposed to such offensive and obscene materials. It also is possible for others to obtain personal information about You on the public forum due to your use of the Site, and that the recipient may use such information to harass or injure You. We do not approve of such unauthorized uses but by using the Site. You acknowledge and agree that We shall not responsible for the use of any personal information that You publicly disclose or share with others on the Site. Please carefully select the type of information that You publicly disclose or share with others on the Site, or from the Site on other social platforms (eg, but not limited to Facebook).</li>
                        <li>We shall have all the rights to take necessary action and claim damages that may occur due to Your involvement/participation in any way on Your own or through group/s of people, intentionally or unintentionally in DoS/DDoS (Distributed Denial of Services).</li>
                        <li>Top4’s performance of this T&Cs is subject to existing laws and legal processes of Government of India, and nothing contained in the T&C is in derogation of Top4’s right to comply with law enforcement requests or requirements relating to your use of this service or information provided to or gathered by Top4 with respect to such use. You agree that Top4 may provide details of your use of the service to regulators or police or to any other third party, or in order to resolve disputes or complaints which relate to the service, at Top4’s complete discretion.</li>
                    </ul>

                    <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">2.8 Contents Posted on Site</h3>
                    <p>All text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music, artwork and computer code (collectively, &quot;Content&quot;), including but not limited to the design, structure, selection, coordination, expression, &quot;look and feel&quot; and arrangement of such Content, contained on the Site is owned, controlled or licensed by or to Us, and is protected by trade dress, copyright, patent and trademark laws, and various other intellectual property rights and unfair competition laws.</p>
                    <p>Except as expressly provided in these T&Cs, no part of the Site and no Content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including &quot;mirroring&quot;) to any other computer, server, website or other medium for publication or distribution or for any commercial enterprise, without Our express prior written consent.</p>
                    <p>You may use information on Our services purposely made available by Us for downloading from the Site, provided that You:</p>
                    <ul className="list-disc pl-5 space-y-1">
                        <li>do not remove any proprietary notice language in all copies of such documents; or</li>
                        <li>use such information only for Your personal, non-commercial informational purpose and do not copy or post such information on any networked computer or broadcast it in any media; or</li>
                        <li>make no modifications to any such information; or do not make any additional representations or warranties relating to such documents.</li>
                    </ul>
                    <p>You shall be responsible for any notes, messages, e-mails, billboard postings, photos, drawings, profiles, opinions, ideas, images, videos, audio files or other materials or information posted or transmitted to the Sites (“Posted Content”). Such Posted Content will become Our property and You grant Us the worldwide, perpetual and transferable rights in such Posted Content. We shall be entitled to, use the Posted Content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works that may include Posted Content. You agree that any Posted Content may be used by Us in the manner that We deem fit, consistant with Applicable Laws and You are not entitled to any payment or other compensation for such use of Posted Content by Us.</p>

                </div>
            </div>
        </div>
    );
}
